// Generated by pipeline/lesson_voice.py
import ep00 from "./ep00.json";
import ep01 from "./ep01.json";
import ep02 from "./ep02.json";
import ep03 from "./ep03.json";
import ep04 from "./ep04.json";
import ep05 from "./ep05.json";
import ep06 from "./ep06.json";
import ep07 from "./ep07.json";
import ep08 from "./ep08.json";
import ep09 from "./ep09.json";
import ep10 from "./ep10.json";
import ep11 from "./ep11.json";

export const timelines = [ep00, ep01, ep02, ep03, ep04, ep05, ep06, ep07, ep08, ep09, ep10, ep11];
